redis:
  enabled: true
  host: localhost
  port: 6379
  password: ""
chat:
  format: "%luckperms_prefix%&x&f&4&f&4&f&4%player_name% &x&d&1&d&1&d&1»&x&f&4&f&4&f&4 " # doesn't support MiniMessage
strikes:
  enabled: true
  max_strikes: 3
  strikes_action: "tempmute %player_name% 10m -s"
  message: "You were punished for receiving 3 chat strikes"
  cooldown: 3600 # seconds, time before strikes are reset
revision:
  enabled: true
  message: "Your message is being revised by server moderators!"
checks:
  delay:
    enabled: true
    strike: false
    time: 3 # seconds, delay between messages
    message: "You have to wait 3 seconds between messages!"
  profanity:
    enabled: true
    strike: true
    replace: true
    message: "Profanity is not allowed! Current chat strikes: %hchatplus_strikes%/3"
  unicode: # denies players of sending unicode characters
    enabled: true
    strike: false
    replace: false
    message: "You can't use unicode characters!" # default color is red
    blacklist:
      - "§"
    whitelist:
      - "è"
      - "é"
      - "à"
      - "ò"
      - "ù"
      - "ì"
      - "ç"
  caps:
    enabled: true
    strike: false
    replace: true
    percentage: 70 # over 70% of uppercase letters will turn message in lower case
    message: "Your message was set in lower case to make it more readable!"
  repetition:
    enabled: true
    strike: false
    replace: true
    max_letters: 3 # allows maximum of 3 of the same letter in a row
    message: "Your message was modified to make it more readable!"
  server_ips:
    enabled: true
    strike: false
    replace: false
    regex: "([0-9]{1,3}\\.){3}[0-9]{1,3}" # regex to match ip addresses
    message: "You can't send ip addresses!"
  links:
    enabled: true
    strike: true
    replace: false
    blacklist_message: "The link you were trying to send is not allowed! Chat strikes: %hchatplus_strikes%/3"
    short_link: "&b&nLink..." # doesn't support MiniMessage
    whitelist:
      - "https://www.spigotmc.org"
      - "https://www.google.com"
      - "https://www.youtube.com"
      - "https://www.github.com"
      - "https://www.twitter.com"
      - "https://www.facebook.com"
      - "https://www.instagram.com"
    blacklist:
      - "adf.ly"
      - "bit.ly"
      - "grabify.link"
      - "tinyurl.com"
      - "iplogger.org"
      - "pornhub.com"
      - "xvideos.com"
      - "xhamster.com"
      - "youporn.com"
      - "xnxx.com"
      - "redtube.com"
      - "mega.nz"